<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="8.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.12" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="assets\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Content Remove="assets\PokemonIcons.ttf" />
	</ItemGroup>

	<ItemGroup>
		<None Update="data_raw\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="assets\PokemonIcons.ttf">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>

</Project>